name: Test

on: push
env:
  github_event_name_var: ${{ github.event_name }}
  github_actor_name_var: ${{ github.actor }}

jobs:
  display-variables:
    steps:
      - name: event name
        run: echo "Variable for event name ${{ github_event_name_var }}"
      - name: actor name
        run: echo "Variable for actor name ${{ github_actor_name_var }}"
